meta_product_name: "Iris Wolfisberg - Portfolio"
meta_title: "Iris Wolfisberg - Portfolio"
meta_description: "A portfolio with my work, skills and contact information."
meta_image: "cover.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
